# Copied from /cvmfs/lhcb.cern.ch/lib/lhcb/MOORE/MOORE_v58r2/InstallArea/x86_64_v3-el9-gcc13+detdesc-opt+g/../../.pre-commit-config.yaml
repos:
-   repo: local
    hooks:
    -   id: test-inputs-use-testfiledb
        name: test inputs use TestFileDB
        description: make sure all inputs to test options files are going through FileTestDB
        language: pygrep
        types_or: [python, yaml]
        exclude: "(.pre-commit-config.yaml|Hlt/Hlt2Conf/python/Hlt2Conf/tests/bandwidth/bandwidth_helpers.py)"
        entry: 'eoslhcb.cern.ch//eos/lhcb/'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.1
    hooks:
    # Run the linter.
    -   id: ruff
        args: [ --fix ]
    # Run the formatter.
    -   id: ruff-format
-   repo: "https://gitlab.cern.ch/lhcb-core/LbDevTools.git"
    rev: 2.1.4
    hooks:
      - id: lb-add-copyright
        exclude: "^lhcbproject.yml$"
